export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const GET_CART_REQUEST = "GET_CART_REQUEST,";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS"; 
export const GET_CART_FAILURE = "GET_CART_FAILURE";

export const CLEAR_LOCAL_STORAGE = "CLEAR_LOCAL_STORAGE";
export const REMOVE_ITEM_FROM_LOCAL_STORAGE = "REMOVE_ITEM_FROM_LOCAL_STORAGE";
export const UPDATE_ITEM_LOCAL_STORAGE = "UPDATE_ITEM_LOCAL_STORAGE";